let g:pymode_lint = 1
let g:pymode_options = 1
let g:pymode_rope = 0
let g:pymode_folding = 0
let g:pymode_completion = 0
let g:pymode_rope_complete_on_dot = 0
let g:pymode_syntax_slow_sync = 0
let g:pymode_lint_on_fly = 0
let g:pymode_lint_ignore="E402,C901,E731"
let g:pymode_rope_complete_on_dot=0
let g:pymode_breakpoint_bind='<leader>x'
