" vim-plug
call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-fugitive'
"Plug 'klen/python-mode', { 'for' : 'python' }
Plug 'klen/python-mode', { 'branch' : 'develop' }
Plug 'jeetsukumaran/vim-buffergator'
Plug 'scrooloose/nerdtree', { 'on' : 'NERDTreeToggle' }
Plug 'flazz/vim-colorschemes'
Plug 'scrooloose/nerdcommenter'
" Plug 'vim-airline/vim-airline'
" Plug 'vim-airline/vim-airline-themes'
call plug#end()

if $DOTFILES_SETUP == "1"
    PlugInstall
endif

" appearance
au BufWinEnter * highlight WhitespaceError ctermbg=red guibg=red
au BufWinEnter * let w:m3=matchadd('WhitespaceError', '\s\+$', -1)
set cursorline
set colorcolumn=80
colorscheme lucius
:LuciusWhiteHighContrast

" configure nerdcommenter
vmap <Leader>c <Plug>NERDCommenterInvert
nmap <Leader>c <Plug>NERDCommenterInvert
let NERDCreateDefaultMappings=0
let NERDSpaceDelims=1

" configure airline
" let g:airline_powerline_fonts=1

" behavior
set hidden
set wildmode=longest:full,list
set tags=tags,./tags,../tags,../../tags,../../../tags,../../../../tags,../../../../../tags
set autochdir

set tw=78
set tabstop=4
set shiftwidth=4
set expandtab
set formatoptions=tcqo2nr
set autoindent
set backspace=eol,start,indent
set cino=:0

set incsearch
set ignorecase
set smartcase

set number
set nowrap
set sidescroll=5
set listchars+=precedes:<,extends:>
set showmatch

set laststatus=2
set statusline=[%N]\ %f\ [%{&fileencoding}][%{&fileformat}]%m%r%y\ \|\ %L\ lines\ (%P)\ \|\ %l,%c

