#!/bin/bash

# if [[ -n "$SSH_AUTH_SOCK" ]]; then
#     mkdir -p $HOME/.ssh_auth_socks
#     PROXY_AUTH_SOCK=$HOME/.ssh_auth_socks/ssh_auth_sock.$HOSTNAME
#     proxy_sock_ok=0
#     if [[ -h "$PROXY_AUTH_SOCK" ]]; then
#         real_sock=$(readlink -f $PROXY_AUTH_SOCK)
#         if [[ -n "$real_sock" && -S "$real_sock" ]]; then
#             proxy_sock_ok=1
#         fi
#     fi
#     if [[ "$proxy_sock_ok" == "0" ]]; then
#         rm -f $PROXY_AUTH_SOCK
#         ln -sf $SSH_AUTH_SOCK $PROXY_AUTH_SOCK
#     fi
#     export SSH_AUTH_SOCK=
# fi
